name: Update Badges

on:
  workflow_run:
    workflows:
      - Flutter CI
    types:
      - completed

permissions:
  contents: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run_id: ${{ github.event.workflow_run.id }}
          name: coverage-report
          path: artifacts/coverage

      - name: Generate coverage badge
        uses: cicirello/coverage-badges-action@v4
        with:
          lcov-file: artifacts/coverage/lcov.info
          output: badges
          coverage-badge-filename: coverage.svg

      - name: Generate quality badge
        uses: emibcn/badge-action@v2
        with:
          label: quality
          status: passing
          color: 4CAF50
          path: badges/quality.svg

      - name: Publish badges branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: badges
          publish_dir: badges
          keep_files: true
